/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package ${class.packageName};

<#list class.imports as importClass>
import ${importClass.name};    
</#list>

<#list class.annotationTypes as annotationType>
@${annotationType.type.simpleName}    
</#list>
public class ${class.className}${class.implementsDecl}${class.extendsDecl} {

    <#if class.serializable>
    private static final long serialVersionUID = 1L;
    </#if>

    <#list class.properties as property>
    private ${property};
    </#list>
    <#list class.constructors as constructor>

    public ${class.className}${constructor.paramSignature} {
        ${constructor.body}
    }
    </#list>
    <#list class.methods as method>

    public ${method.returnType} ${method.methodName}${method.paramSignature} {
        ${method.body}
    }
    <#if method.parameters?size == 1 && method.parameters[0].type.type.name == "java.util.List">

    <#assign jType = method.parameters[0].type>
    <#assign varName = method.parameters[0].name>
    public ${method.returnType} add${varName?cap_first}(${jType.genericType.simpleName} ${varName}) {
        if(this.${varName} == null) {
           this.${varName} = new java.util.ArrayList<${jType.genericType.simpleName}>();
           this.${varName}.add(${varName});
        } else {
           this.${varName}.add(${varName});
        }
        return this;
    }
    </#if>
    </#list>
}